spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  devtools:
    livereload:
      enabled: true

  profiles:
    include: oauth
#
#  mvc:
#    static-path-pattern: /static/**

server:
  servlet:
    encoding:
      force: true