spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  devtools:
    livereload:
      enabled: true

  profiles:
    include: oauth

  session:
    store-type: jdbc

#  mvc:
#    static-path-pattern: /static/**

server:
  servlet:
    session:
      timeout: 100000 # 세션 시간 초과. 기간 접미사가 지정되지 않으면 초가 사용됩니다.
    encoding:
      force: true